//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mass_helper
{
    
    
    /// <summary>
    /// The openMass Configuration Section.
    /// </summary>
    public partial class openMass : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the openMass Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string openMassSectionName = "openMass";
        
        /// <summary>
        /// The XML path of the openMass Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string openMassSectionPath = "massProblems/openMass";
        
        /// <summary>
        /// Gets the openMass instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public static global::Mass_helper.openMass Instance
        {
            get
            {
                return ((global::Mass_helper.openMass)(global::System.Configuration.ConfigurationManager.GetSection(global::Mass_helper.openMass.openMassSectionPath)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Mass_helper.openMass.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::Mass_helper.openMass.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region CreditBroker Property
        /// <summary>
        /// The XML name of the <see cref="CreditBroker"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string CreditBrokerPropertyName = "creditBroker";
        
        /// <summary>
        /// Gets or sets the CreditBroker.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The CreditBroker.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Mass_helper.openMass.CreditBrokerPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Mass_helper.creditBroker CreditBroker
        {
            get
            {
                return ((global::Mass_helper.creditBroker)(base[global::Mass_helper.openMass.CreditBrokerPropertyName]));
            }
            set
            {
                base[global::Mass_helper.openMass.CreditBrokerPropertyName] = value;
            }
        }
        #endregion
        
        #region SBankV Property
        /// <summary>
        /// The XML name of the <see cref="SBankV"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string SBankVPropertyName = "sBankV";
        
        /// <summary>
        /// Gets or sets the SBankV.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The SBankV.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Mass_helper.openMass.SBankVPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Mass_helper.SBankV SBankV
        {
            get
            {
                return ((global::Mass_helper.SBankV)(base[global::Mass_helper.openMass.SBankVPropertyName]));
            }
            set
            {
                base[global::Mass_helper.openMass.SBankVPropertyName] = value;
            }
        }
        #endregion
        
        #region SBankP Property
        /// <summary>
        /// The XML name of the <see cref="SBankP"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string SBankPPropertyName = "sBankP";
        
        /// <summary>
        /// Gets or sets the SBankP.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The SBankP.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Mass_helper.openMass.SBankPPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Mass_helper.SBankP SBankP
        {
            get
            {
                return ((global::Mass_helper.SBankP)(base[global::Mass_helper.openMass.SBankPPropertyName]));
            }
            set
            {
                base[global::Mass_helper.openMass.SBankPPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Mass_helper
{
    
    
    /// <summary>
    /// Кредитный Брокер
    /// </summary>
    public partial class creditBroker : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region to Property
        /// <summary>
        /// The XML name of the <see cref="to"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string toPropertyName = "to";
        
        /// <summary>
        /// Gets or sets the to.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The to.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Mass_helper.creditBroker.toPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false, DefaultValue="ML.IT.CreditBrokerTechAlerts@maxus.ru")]
        public virtual string to
        {
            get
            {
                return ((string)(base[global::Mass_helper.creditBroker.toPropertyName]));
            }
            set
            {
                base[global::Mass_helper.creditBroker.toPropertyName] = value;
            }
        }
        #endregion
        
        #region copy Property
        /// <summary>
        /// The XML name of the <see cref="copy"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string copyPropertyName = "copy";
        
        /// <summary>
        /// Gets or sets the copy.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The copy.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Mass_helper.creditBroker.copyPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string copy
        {
            get
            {
                return ((string)(base[global::Mass_helper.creditBroker.copyPropertyName]));
            }
            set
            {
                base[global::Mass_helper.creditBroker.copyPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Mass_helper
{
    
    
    /// <summary>
    /// Связной Банк (выдача карт, оформление де-позитов)
    /// </summary>
    public partial class SBankV : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region TO Property
        /// <summary>
        /// The XML name of the <see cref="TO"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string TOPropertyName = "tO";
        
        /// <summary>
        /// Gets or sets the TO.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The TO.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Mass_helper.SBankV.TOPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false, DefaultValue="ML.IT.BankTechAlerts@maxus.ru;")]
        public virtual string TO
        {
            get
            {
                return ((string)(base[global::Mass_helper.SBankV.TOPropertyName]));
            }
            set
            {
                base[global::Mass_helper.SBankV.TOPropertyName] = value;
            }
        }
        #endregion
        
        #region COPY Property
        /// <summary>
        /// The XML name of the <see cref="COPY"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string COPYPropertyName = "cOPY";
        
        /// <summary>
        /// Gets or sets the COPY.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The COPY.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Mass_helper.SBankV.COPYPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false, DefaultValue="ML.OK.Info.Roznica@maxus.ru")]
        public virtual string COPY
        {
            get
            {
                return ((string)(base[global::Mass_helper.SBankV.COPYPropertyName]));
            }
            set
            {
                base[global::Mass_helper.SBankV.COPYPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Mass_helper
{
    
    
    /// <summary>
    /// Связной Банк (попол-нение карт)
    /// </summary>
    public partial class SBankP : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region TO Property
        /// <summary>
        /// The XML name of the <see cref="TO"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string TOPropertyName = "tO";
        
        /// <summary>
        /// Gets or sets the TO.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The TO.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Mass_helper.SBankP.TOPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false, DefaultValue="ML.IT.BankTechAlerts@maxus.ru;")]
        public virtual string TO
        {
            get
            {
                return ((string)(base[global::Mass_helper.SBankP.TOPropertyName]));
            }
            set
            {
                base[global::Mass_helper.SBankP.TOPropertyName] = value;
            }
        }
        #endregion
        
        #region COPY Property
        /// <summary>
        /// The XML name of the <see cref="COPY"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string COPYPropertyName = "cOPY";
        
        /// <summary>
        /// Gets or sets the COPY.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The COPY.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Mass_helper.SBankP.COPYPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false, DefaultValue="ML.OK.Info.Roznica@maxus.ru")]
        public virtual string COPY
        {
            get
            {
                return ((string)(base[global::Mass_helper.SBankP.COPYPropertyName]));
            }
            set
            {
                base[global::Mass_helper.SBankP.COPYPropertyName] = value;
            }
        }
        #endregion
    }
}
